name: Build and Test Wi-Fi Latency Application

on:
  push:
    branches: [ main, test-build-workflow ]
  pull_request:
    branches: [ main ]

jobs:
  set-image-tag:
    runs-on: ubuntu-22.04
    outputs:
      IMAGE_TAG: ${{ steps.set-output.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout wifi latency test repository
        uses: actions/checkout@v4
        with:
          path: app-workspace/wifi_latency_test

      - name: Prepare west project
        working-directory: app-workspace
        run: |
          python3 -m pip install west
          west init -l wifi_latency_test
          west update -o=--depth=1 -n

      - name: Find toolchain bundle id
        id: set-output
        working-directory: app-workspace
        run: echo "IMAGE_TAG=$(./nrf/scripts/print_toolchain_checksum.sh)" >> $GITHUB_OUTPUT
      
      - name: Display GITHUB_OUTPUT content
        working-directory: app-workspace
        run: |
          echo "Contents of GITHUB_OUTPUT:"
          cat $GITHUB_OUTPUT

  build-and-test-in-docker:
    needs: set-image-tag
    runs-on: ubuntu-22.04
    container: ghcr.io/nrfconnect/sdk-nrf-toolchain:v3.0.2
    defaults:
      run:
        # Bash shell is needed to set toolchain related environment variables in docker container
        # It is a workaround for GitHub Actions limitation https://github.com/actions/runner/issues/1964
        shell: bash
    strategy:
      matrix:
        config:
          # UDP Tests
          - name: "UDP TX Station"
            overlay: "overlay-udp-tx-sta.conf"
            description: "UDP TX device in station mode"
          - name: "UDP RX Station" 
            overlay: "overlay-udp-rx-sta.conf"
            description: "UDP RX device in station mode"
          - name: "UDP RX SoftAP"
            overlay: "overlay-udp-rx-softap.conf"
            description: "UDP RX device in SoftAP mode"
          # Raw Packet Tests
          - name: "Raw TX Non-Connected"
            overlay: "overlay-raw-tx-sta-non-conn.conf"
            description: "Raw TX device in non-connected mode"
          - name: "Raw RX Monitor"
            overlay: "overlay-raw-rx-monitor.conf"
            description: "Raw RX device in monitor mode"
    
    steps:
      - name: Checkout wifi latency test repository
        uses: actions/checkout@v4
        with:
          path: app-workspace/wifi_latency_test

      - name: Prepare west project
        working-directory: app-workspace
        run: |
          west init -l wifi_latency_test
          west update -o=--depth=1 -n

      - name: Build ${{ matrix.config.name }}
        working-directory: app-workspace/wifi_latency_test
        run: |
          west build -p -b nrf7002dk/nrf5340/cpuapp -- -DEXTRA_CONF_FILE=${{ matrix.config.overlay }}

      - name: Upload build artifacts for ${{ matrix.config.name }}
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-${{ matrix.config.name }}
          path: |
            app-workspace/wifi_latency_test/build/zephyr/zephyr.hex
            app-workspace/wifi_latency_test/build/zephyr/zephyr.elf
            app-workspace/wifi_latency_test/build/zephyr/zephyr.bin

  validate-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: app-workspace/wifi_latency_test
        
      - name: Validate README structure
        working-directory: app-workspace/wifi_latency_test
        run: |
          # Check if README has required sections as specified in the documentation
          echo "Validating README.md structure..."
          
          # Required sections from the actual README
          grep -q "🔍 Overview" README.md || (echo "Missing Overview section" && exit 1)
          grep -q "🎯 Key Features" README.md || (echo "Missing Key Features section" && exit 1)
          grep -q "🧪 Test Scenarios" README.md || (echo "Missing Test Scenarios section" && exit 1)
          grep -q "🔧 Hardware Requirements" README.md || (echo "Missing Hardware Requirements section" && exit 1)
          grep -q "🚀 Quick Start Guide" README.md || (echo "Missing Quick Start Guide section" && exit 1)
          grep -q "⚙️ Configuration Guide" README.md || (echo "Missing Configuration Guide section" && exit 1)
          grep -q "🎮 Operation Guide" README.md || (echo "Missing Operation Guide section" && exit 1)
          grep -q "📏 Precision Timing Measurement" README.md || (echo "Missing Precision Timing Measurement section" && exit 1)
          grep -q "📊 Test Results and Performance Analysis" README.md || (echo "Missing Test Results section" && exit 1)
          
          echo "README.md validation passed ✓"

      - name: Validate configuration files exist
        working-directory: app-workspace/wifi_latency_test
        run: |
          echo "Checking overlay configuration files..."
          
          # UDP configurations
          [ -f overlay-udp-tx-sta.conf ] || (echo "Missing overlay-udp-tx-sta.conf" && exit 1)
          [ -f overlay-udp-rx-sta.conf ] || (echo "Missing overlay-udp-rx-sta.conf" && exit 1)
          [ -f overlay-udp-rx-softap.conf ] || (echo "Missing overlay-udp-rx-softap.conf" && exit 1)
          
          # Raw packet configurations
          [ -f overlay-raw-tx-sta-non-conn.conf ] || (echo "Missing overlay-raw-tx-sta-non-conn.conf" && exit 1)
          [ -f overlay-raw-rx-monitor.conf ] || (echo "Missing overlay-raw-rx-monitor.conf" && exit 1)
          
          # Base configuration
          [ -f prj.conf ] || (echo "Missing prj.conf" && exit 1)
          
          # West configuration
          [ -f west.yml ] || (echo "Missing west.yml" && exit 1)
          
          echo "Configuration files validation passed ✓"

      - name: Check license headers in source files
        working-directory: app-workspace/wifi_latency_test
        run: |
          echo "Validating license headers..."
          
          # Check that source files have proper license headers
          missing_headers=0
          
          for file in $(find src/ -name "*.c" -o -name "*.h"); do
            if ! grep -q "SPDX-License-Identifier: LicenseRef-Nordic-5-Clause" "$file"; then
              echo "Missing license header in: $file"
              missing_headers=$((missing_headers + 1))
            fi
          done
          
          if [ $missing_headers -gt 0 ]; then
            echo "❌ $missing_headers files missing license headers"
            exit 1
          fi
          
          echo "License header validation passed ✓"

      - name: Validate Python analysis script
        working-directory: app-workspace/wifi_latency_test
        run: |
          echo "Checking PPK2 analysis script..."
          
          [ -f script/ppk_record_analysis.py ] || (echo "Missing PPK2 analysis script" && exit 1)
          
          # Basic syntax check
          python3 -m py_compile script/ppk_record_analysis.py || (echo "PPK2 analysis script has syntax errors" && exit 1)
          
          echo "Python script validation passed ✓"

  static-analysis:
    needs: set-image-tag
    runs-on: ubuntu-24.04
    container: ghcr.io/nrfconnect/sdk-nrf-toolchain:${{ needs.set-image-tag.outputs.IMAGE_TAG }}
    defaults:
      run:
        # Bash shell is needed to set toolchain related environment variables in docker container
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: app-workspace/wifi_latency_test
        
      - name: Prepare west project for style checks
        working-directory: app-workspace
        run: |
          west init -l wifi_latency_test
          west update -o=--depth=1 -n
          
      - name: Run Zephyr checkpatch
        working-directory: app-workspace
        run: |
          echo "Running Zephyr checkpatch on source files..."
          
          # Check if we have any commits to validate
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
            # Run checkpatch on the diff between HEAD and previous commit
            cd wifi_latency_test && git diff HEAD~1 | ../zephyr/scripts/checkpatch.pl --no-tree -
          else
            # For initial commit or single commit, check all source files
            echo "Single commit detected, checking all source files..."
            for file in $(find wifi_latency_test/src/ -name "*.c" -o -name "*.h"); do
              if [ -f "$file" ]; then
                echo "Checking $file..."
                ./zephyr/scripts/checkpatch.pl --no-tree --file "$file" || true
              fi
            done
          fi
          
          echo "Checkpatch analysis completed ✓"
          
      - name: Check code formatting with Zephyr style
        working-directory: app-workspace
        run: |
          echo "Checking code formatting with Zephyr .clang-format..."
          
          # Use Zephyr's .clang-format configuration
          if [ -f zephyr/.clang-format ]; then
            cp zephyr/.clang-format wifi_latency_test/.clang-format
          else
            echo "Warning: Zephyr .clang-format not found, using project default"
          fi
          
          # Find C and H files
          c_files=$(find wifi_latency_test/src/ -name "*.c" -o -name "*.h")
          
          if [ -n "$c_files" ]; then
            echo "Found files to check:"
            echo "$c_files"
            
            # Check formatting (dry-run mode)
            format_issues=0
            for file in $c_files; do
              if ! clang-format --dry-run --Werror "$file" >/dev/null 2>&1; then
                echo "❌ Formatting issues found in: $file"
                clang-format --dry-run "$file" | head -20
                format_issues=$((format_issues + 1))
              else
                echo "✓ $file"
              fi
            done
            
            if [ $format_issues -gt 0 ]; then
              echo ""
              echo "❌ Found formatting issues in $format_issues file(s)"
              echo "Run 'clang-format -i <file>' to fix formatting issues"
              exit 1
            fi
            
            echo "Code formatting check passed ✓"
          else
            echo "No C/H files found to check"
          fi 
